# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 47303ee046e5d6387df481a577bd353d6726417e0b486dfd3c1a930fc6d3961957abf3f879ef0db7d935c6c89ee34b8b374f88be595fa8c574aa696121765722

test:
  secret_key_base: b3e2ff6f7823aaeaffb9845ca096ffdf49a87cfc9a889ef494e508c641cf6d92af3439d2820afe02aaadbec49b6f17621646362407d696474781a80ee452af72

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
